print("第一位同學 : ")
name1 = str(input())
print("第一位成績 : ")
score1 = int(input())
print("第二位同學 : ")
name2 = str(input())
print("第二位成績 : ")
score2 = int(input())
print(    "name    score")
print(name1 + "    ", score1)
print(name2 + "    ", score2)
print("Total score is : ", score1 + score2)
